version: '2'

services:
   app: 
      image: java-inventory-app
      depends_on:
         - mongo
      networks:
         - my-network-1
   mongo: 
      image: mongo:5
      container_name: mongo
      networks:
         - my-network-1
      
networks:
   my-network-1:
      driver: bridge