name: Java CI with Maven for PR

on: 
   pull_request:
   
jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            os: [macos-latest, windows-latest]
      
      name: Build with Java 11 on ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: 11
      - name: Build with Maven
        run: mvn -f inventory/pom.xml clean verify