name: Java CI with Maven and Docker in macOS

on:
   push:
   pull_request:

jobs: 
   build: 
      runs-on: macos-latest
      
      name: Build in macOS
      steps: 
      - uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with: 
           java-version: 11
           distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with: 
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
           restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn verify
        working-directory: inventory
        env:
           TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock