name: Java CI with Maven, Docker, and SonarCloud in Linux

on:
   push:
   pull_request:
   
jobs:
   build:
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
        with: 
           fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with: 
           java-version: 8
           distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with: 
           path: |
              ~/.m2
              ~/.sonar/cache
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
           restore-keys: ${{ runner.os }}-m2-
      - name: Set Maven Additional Goals
        run: echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV
        if: ${{ env.SONAR_TOKEN }}
      - name: Build with Maven and Sonar Cloud
        run: > 
           xvfb-run mvn verify $SONARGOAL
           -Dsonar.organization=bakhamadiev
           -Dsonar.host.url=https://sonarcloud.io
           -Dsonar.projectKey=BakhaMadiev_tddProject
           -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report 
        working-directory: inventory
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}