name: Java CI with Maven, Docker, and SonarCloud in Linux

on:
   push:
   pull_request:
   
jobs:
   build:
      runs-on: ubuntu-latest
      strategy: 
         matrix:
            java: [8, 11, 17]
            
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      
      steps:
      - uses: actions/checkout@v4
        with: 
           fetch-depth: 0
           
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with: 
           java-version: ${{ matrix.java }}
           distribution: 'temurin'
           
      - name: Cache Maven packages
        uses: actions/cache@v4
        with: 
           path: |
              ~/.m2
              ~/.sonar/cache
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
           restore-keys: ${{ runner.os }}-m2-
           
      # Build on Java 8
      # Coveralls is not up (server returns 500) Removed for now
      - name: Build Maven with Coveralls (Java 8)
        if: matrix.java == 8
        run: xvfb-run mvn verify -Pjacoco jacoco:report -Pcoveralls -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report
        working-directory: inventory
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
           
      - name: Archive Jacoco report
        if: matrix.java == 8
        uses: actions/upload-artifact@v4
        with: 
           name: jacoco-report-java8
           path: inventory/target/site/jacoco/jacoco.xml
           
      #Build on Java 11
      - name: Build Maven with PIT Mutation testing and surefire report generation
        if: matrix.java == 11
        run: xvfb-run mvn verify org.pitest:pitest-maven:mutationCoverage surefire-report:report-only
        working-directory: inventory
      
      - name: Archive PIT report for java 11
        if: matrix.java == 11
        uses: actions/upload-artifact@v4
        with:
           name: pit-report-java11
           path: inventory/target/pit-reports
           
      - name: Archive JUnit report
        if: matrix.java == 11
        uses: actions/upload-artifact@v4
        with: 
           name: junit-report-java11
           path: inventory/target/surefire-reports
        
      # Build on Java 17
      - name: Build Maven with Sonarcloud
        if: matrix.java == 11
        run: >
           xvfb-run mvn verify -Pjacoco sonar:sonar
           -Dsonar.organization=bakhamadiev
           -Dsonar.host.url=https://sonarcloud.io
           -Dsonar.projectKey=BakhaMadiev_tddProject
        working-directory: inventory
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}