name: Java CI with Maven in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matix.os }}}
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, macis-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Build with Java ${{ matix.java }} on ${{ matrix.os }}
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -f inventory/pom.xml clean test verify
